version: '3.8'
services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: imdb_flask_app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./data:/data
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: imdb_mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db

volumes:
  mongo_data:
